/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/features/theme/hexlode-theme.ts
 * Command: astryx theme build src/features/theme/hexlode-theme.ts --out src/features/theme/hexlode-theme.css
 * Generated: 2026-09-27T14:15:53.802Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
