/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/features/theme/hexlode-theme.ts
 * Command: astryx theme build src/features/theme/hexlode-theme.ts --out src/features/theme/hexlode-theme.css
 * Generated: 2026-09-27T14:15:53.803Z
 */

/// <reference path="./hexlode.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const themeIcons: IconRegistry;
export declare const hexlodeTheme: DefinedTheme;
