/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as CropRouteImport } from './routes/crop'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResizeRouteImport } from './routes/resize'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StripMetadataRouteImport } from './routes/strip-metadata'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ToolsPipelineIdRouteImport } from './routes/tools.$pipelineId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRoute = CropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeRoute = ResizeRouteImport.update({
  id: '/resize',
  path: '/resize',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StripMetadataRoute = StripMetadataRouteImport.update({
  id: '/strip-metadata',
  path: '/strip-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPipelineIdRoute = ToolsPipelineIdRouteImport.update({
  id: '/tools/$pipelineId',
  path: '/tools/$pipelineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/crop': typeof CropRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/resize': typeof ResizeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rotate': typeof RotateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strip-metadata': typeof StripMetadataRoute
  '/studio': typeof StudioRoute
  '/api/health': typeof ApiHealthRoute
  '/tools/$pipelineId': typeof ToolsPipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/crop': typeof CropRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/resize': typeof ResizeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rotate': typeof RotateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strip-metadata': typeof StripMetadataRoute
  '/studio': typeof StudioRoute
  '/api/health': typeof ApiHealthRoute
  '/tools/$pipelineId': typeof ToolsPipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/crop': typeof CropRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/resize': typeof ResizeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rotate': typeof RotateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strip-metadata': typeof StripMetadataRoute
  '/studio': typeof StudioRoute
  '/api/health': typeof ApiHealthRoute
  '/tools/$pipelineId': typeof ToolsPipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/convert'
    | '/crop'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/resize'
    | '/robots.txt'
    | '/rotate'
    | '/sitemap.xml'
    | '/strip-metadata'
    | '/studio'
    | '/api/health'
    | '/tools/$pipelineId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/convert'
    | '/crop'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/resize'
    | '/robots.txt'
    | '/rotate'
    | '/sitemap.xml'
    | '/strip-metadata'
    | '/studio'
    | '/api/health'
    | '/tools/$pipelineId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/convert'
    | '/crop'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/resize'
    | '/robots.txt'
    | '/rotate'
    | '/sitemap.xml'
    | '/strip-metadata'
    | '/studio'
    | '/api/health'
    | '/tools/$pipelineId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  ConvertRoute: typeof ConvertRoute
  CropRoute: typeof CropRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PrivacyRoute: typeof PrivacyRoute
  ResizeRoute: typeof ResizeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RotateRoute: typeof RotateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StripMetadataRoute: typeof StripMetadataRoute
  StudioRoute: typeof StudioRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ToolsPipelineIdRoute: typeof ToolsPipelineIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop': {
      id: '/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof CropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize': {
      id: '/resize'
      path: '/resize'
      fullPath: '/resize'
      preLoaderRoute: typeof ResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strip-metadata': {
      id: '/strip-metadata'
      path: '/strip-metadata'
      fullPath: '/strip-metadata'
      preLoaderRoute: typeof StripMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$pipelineId': {
      id: '/tools/$pipelineId'
      path: '/tools/$pipelineId'
      fullPath: '/tools/$pipelineId'
      preLoaderRoute: typeof ToolsPipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  ConvertRoute: ConvertRoute,
  CropRoute: CropRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PrivacyRoute: PrivacyRoute,
  ResizeRoute: ResizeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RotateRoute: RotateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StripMetadataRoute: StripMetadataRoute,
  StudioRoute: StudioRoute,
  ApiHealthRoute: ApiHealthRoute,
  ToolsPipelineIdRoute: ToolsPipelineIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
